version: '3'
services:

  game:
    build: ./Game
    environment:
      - VILAINS_URL=http://vilains:5001
      - LICORNES_URL=http://licornes:6001
    ports:
      - "6666:3000"

  heros:
    build: ./Heros
    environment:
      - TRACKEUR_URL=http://trackeur:5002
      - FOURNISSEUR_URL=http://fournisseur:6002
    ports:
      - "5000:5000"
    
  vilains:
    build: ./Vilains
    environment:
      - TRACKEUR_URL=http://trackeur:5002
    ports:
      - "5001:5001"

  trackeur:
    build: ./Trackeur
    environment:
      - HEROS_URL=http://heros:5000
    ports:
      - "5002:5002"

  licornes:
    build: ./Licornes
    environment:
      - FOURNISSEUR_URL=http://fournisseur:6002
    ports:
      - "6001:6001"

  fournisseur:
    build: ./Fournisseur
    environment:
      - HEROS_URL=http://heros:5000
    ports:
      - "6002:6002"
