version: '3'
services:

  game:
    build: ./Game
    environment:
      - VILAINS_URL=http://vilains:5001
    ports:
      - "6666:3000"

  heros:
    build: ./Heros
    environment:
      - TRACKEUR_URL=http://trackeur:5002
    ports:
      - "5000:5000"
    
  vilains:
    build: ./Vilains
    environment:
      - TRACKEUR_URL=http://trackeur:5002
    ports:
      - "5001:5001"

  trackeur:
    build: ./Trackeur
    environment:
      - HEROS_URL=http://heros:5000
    ports:
      - "5002:5002"
